const data = [
	{
		id: 1,
		name: "Introduction to Programming",
		title: "A comprehensive guide to the basics of programming.",
		price: 29.99,
		category: "Programming",
		image: "https://picsum.photos/id/25/500/500",
	},
	{
		id: 2,
		name: "Advanced Mathematics",
		title: "An in-depth look at advanced mathematical concepts.",
		price: 49.99,
		category: "Mathematics",
		image: "https://picsum.photos/id/26/500/500",
	},
	{
		id: 3,
		name: "Literary Classics",
		title: "A collection of classic literature.",
		price: 19.99,
		category: "Literature",
		image: "https://picsum.photos/id/27/500/500",
	},
	{
		id: 4,
		name: "Free Book on Gardening",
		title: "A free guide to gardening basics.",
		price: 0.0,
		category: "Free",
		image: "https://picsum.photos/id/28/500/500",
	},
	{
		id: 5,
		name: "History of the World",
		title: "An overview of world history.",
		price: 39.99,
		category: "History",
		image: "https://picsum.photos/id/29/500/500",
	},
	{
		id: 6,
		name: "Science Experiments for Kids",
		title: "Fun and educational science experiments for children.",
		price: 24.99,
		category: "Science",
		image: "https://picsum.photos/id/30/500/500",
	},
	{
		id: 7,
		name: "Free Guide to Healthy Eating",
		title: "A free guide to maintaining a healthy diet.",
		price: 0.0,
		category: "Free",
		image: "https://picsum.photos/id/25/500/500",
	},
	{
		id: 8,
		name: "Understanding Economics",
		title: "A comprehensive introduction to economics.",
		price: 34.99,
		category: "Economics",
		image: "https://picsum.photos/id/26/500/500",
	},
	{
		id: 9,
		name: "Creative Writing Workshop",
		title: "A workshop guide for creative writing.",
		price: 29.99,
		category: "Writing",
		image: "https://picsum.photos/id/27/500/500",
	},
	{
		id: 10,
		name: "Art and Design Basics",
		title: "Basic principles of art and design.",
		price: 27.99,
		category: "Art",
		image: "https://picsum.photos/id/28/500/500",
	},
	{
		id: 11,
		name: "Free Introduction to JavaScript",
		title: "A free guide to learning JavaScript.",
		price: 0.0,
		category: "Free",
		image: "https://picsum.photos/id/29/500/500",
	},
	{
		id: 12,
		name: "Free Basic Cooking Recipes",
		title: "A free collection of basic cooking recipes.",
		price: 0.0,
		category: "Free",
		image: "https://picsum.photos/id/30/500/500",
	},
	{
		id: 13,
		name: "Modern Art Techniques",
		title: "An exploration of modern art techniques.",
		price: 31.99,
		category: "Art",
		image: "https://picsum.photos/id/25/500/500",
	},
	{
		id: 14,
		name: "Introduction to Machine Learning",
		title: "A beginner's guide to machine learning.",
		price: 45.99,
		category: "Programming",
		image: "https://picsum.photos/id/26/500/500",
	},
	{
		id: 15,
		name: "Free Guide to Yoga",
		title: "A free guide to basic yoga practices.",
		price: 0.0,
		category: "Free",
		image: "https://picsum.photos/id/27/500/500",
	},
	{
		id: 16,
		name: "Basic Physics",
		title: "An introduction to basic physics concepts.",
		price: 22.99,
		category: "Science",
		image: "https://picsum.photos/id/28/500/500",
	},
	{
		id: 17,
		name: "The World of Chemistry",
		title: "An overview of fundamental chemistry concepts.",
		price: 27.99,
		category: "Science",
		image: "https://picsum.photos/id/29/500/500",
	},
	{
		id: 18,
		name: "Free Photography Tips",
		title: "A free guide to improving your photography skills.",
		price: 0.0,
		category: "Free",
		image: "https://picsum.photos/id/30/500/500",
	},
	{
		id: 19,
		name: "Learning French",
		title: "A guide to learning the French language.",
		price: 35.99,
		category: "Language",
		image: "https://picsum.photos/id/25/500/500",
	},
	{
		id: 20,
		name: "Free Travel Guide",
		title: "A free guide to popular travel destinations.",
		price: 0.0,
		category: "Free",
		image: "https://picsum.photos/id/26/500/500",
	},
];

export default data;
